# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main/proto/DebugDataFeedServe.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='main/proto/DebugDataFeedServe.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n#main/proto/DebugDataFeedServe.proto\"D\n\x18SphericalVelocityMessage\x12\n\n\x02\x64r\x18\x01 \x02(\x01\x12\x0e\n\x06\x64theta\x18\x02 \x02(\x01\x12\x0c\n\x04\x64phi\x18\x03 \x02(\x01\"T\n\x1bGeographicCoordinateMessage\x12\x10\n\x08\x61ltitude\x18\x01 \x02(\x01\x12\x10\n\x08latitude\x18\x02 \x02(\x01\x12\x11\n\tlongitude\x18\x03 \x02(\x01\"\xa6\x01\n\x14\x41ircraftStateMessage\x12\x12\n\naircraftID\x18\x01 \x02(\t\x12\x0c\n\x04time\x18\x02 \x02(\x03\x12.\n\x08position\x18\x03 \x02(\x0b\x32\x1c.GeographicCoordinateMessage\x12+\n\x08velocity\x18\x04 \x02(\x0b\x32\x19.SphericalVelocityMessage\x12\x0f\n\x07heading\x18\x05 \x02(\x01\"P\n\x12SystemStateMessage\x12\x0c\n\x04time\x18\x01 \x02(\x03\x12,\n\raircraftState\x18\x02 \x03(\x0b\x32\x15.AircraftStateMessageB7\n!com.atc.simulator.ProtocolBuffersB\x12\x44\x65\x62ugDataFeedServe')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SPHERICALVELOCITYMESSAGE = _descriptor.Descriptor(
  name='SphericalVelocityMessage',
  full_name='SphericalVelocityMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dr', full_name='SphericalVelocityMessage.dr', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtheta', full_name='SphericalVelocityMessage.dtheta', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dphi', full_name='SphericalVelocityMessage.dphi', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=107,
)


_GEOGRAPHICCOORDINATEMESSAGE = _descriptor.Descriptor(
  name='GeographicCoordinateMessage',
  full_name='GeographicCoordinateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='altitude', full_name='GeographicCoordinateMessage.altitude', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='GeographicCoordinateMessage.latitude', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='GeographicCoordinateMessage.longitude', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=193,
)


_AIRCRAFTSTATEMESSAGE = _descriptor.Descriptor(
  name='AircraftStateMessage',
  full_name='AircraftStateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aircraftID', full_name='AircraftStateMessage.aircraftID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='AircraftStateMessage.time', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='AircraftStateMessage.position', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='AircraftStateMessage.velocity', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heading', full_name='AircraftStateMessage.heading', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=362,
)


_SYSTEMSTATEMESSAGE = _descriptor.Descriptor(
  name='SystemStateMessage',
  full_name='SystemStateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='SystemStateMessage.time', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aircraftState', full_name='SystemStateMessage.aircraftState', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=444,
)

_AIRCRAFTSTATEMESSAGE.fields_by_name['position'].message_type = _GEOGRAPHICCOORDINATEMESSAGE
_AIRCRAFTSTATEMESSAGE.fields_by_name['velocity'].message_type = _SPHERICALVELOCITYMESSAGE
_SYSTEMSTATEMESSAGE.fields_by_name['aircraftState'].message_type = _AIRCRAFTSTATEMESSAGE
DESCRIPTOR.message_types_by_name['SphericalVelocityMessage'] = _SPHERICALVELOCITYMESSAGE
DESCRIPTOR.message_types_by_name['GeographicCoordinateMessage'] = _GEOGRAPHICCOORDINATEMESSAGE
DESCRIPTOR.message_types_by_name['AircraftStateMessage'] = _AIRCRAFTSTATEMESSAGE
DESCRIPTOR.message_types_by_name['SystemStateMessage'] = _SYSTEMSTATEMESSAGE

SphericalVelocityMessage = _reflection.GeneratedProtocolMessageType('SphericalVelocityMessage', (_message.Message,), dict(
  DESCRIPTOR = _SPHERICALVELOCITYMESSAGE,
  __module__ = 'main.proto.DebugDataFeedServe_pb2'
  # @@protoc_insertion_point(class_scope:SphericalVelocityMessage)
  ))
_sym_db.RegisterMessage(SphericalVelocityMessage)

GeographicCoordinateMessage = _reflection.GeneratedProtocolMessageType('GeographicCoordinateMessage', (_message.Message,), dict(
  DESCRIPTOR = _GEOGRAPHICCOORDINATEMESSAGE,
  __module__ = 'main.proto.DebugDataFeedServe_pb2'
  # @@protoc_insertion_point(class_scope:GeographicCoordinateMessage)
  ))
_sym_db.RegisterMessage(GeographicCoordinateMessage)

AircraftStateMessage = _reflection.GeneratedProtocolMessageType('AircraftStateMessage', (_message.Message,), dict(
  DESCRIPTOR = _AIRCRAFTSTATEMESSAGE,
  __module__ = 'main.proto.DebugDataFeedServe_pb2'
  # @@protoc_insertion_point(class_scope:AircraftStateMessage)
  ))
_sym_db.RegisterMessage(AircraftStateMessage)

SystemStateMessage = _reflection.GeneratedProtocolMessageType('SystemStateMessage', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMSTATEMESSAGE,
  __module__ = 'main.proto.DebugDataFeedServe_pb2'
  # @@protoc_insertion_point(class_scope:SystemStateMessage)
  ))
_sym_db.RegisterMessage(SystemStateMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!com.atc.simulator.ProtocolBuffersB\022DebugDataFeedServe'))
# @@protoc_insertion_point(module_scope)
