// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/DebugDataFeedServe.proto

package com.atc.simulator.DebugDataFeed;

public final class DebugDataFeedServe {
  private DebugDataFeedServe() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AircraftOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Aircraft)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated double position = 1;</code>
     */
    java.util.List<java.lang.Double> getPositionList();
    /**
     * <code>repeated double position = 1;</code>
     */
    int getPositionCount();
    /**
     * <code>repeated double position = 1;</code>
     */
    double getPosition(int index);

    /**
     * <code>required float speed = 2;</code>
     */
    boolean hasSpeed();
    /**
     * <code>required float speed = 2;</code>
     */
    float getSpeed();
  }
  /**
   * Protobuf type {@code Aircraft}
   */
  public static final class Aircraft extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Aircraft)
      AircraftOrBuilder {
    // Use Aircraft.newBuilder() to construct.
    private Aircraft(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Aircraft(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Aircraft defaultInstance;
    public static Aircraft getDefaultInstance() {
      return defaultInstance;
    }

    public Aircraft getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Aircraft(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                position_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              position_.add(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                position_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                position_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 21: {
              bitField0_ |= 0x00000001;
              speed_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          position_ = java.util.Collections.unmodifiableList(position_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.atc.simulator.DebugDataFeed.DebugDataFeedServe.internal_static_Aircraft_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.atc.simulator.DebugDataFeed.DebugDataFeedServe.internal_static_Aircraft_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft.class, com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft.Builder.class);
    }

    public static com.google.protobuf.Parser<Aircraft> PARSER =
        new com.google.protobuf.AbstractParser<Aircraft>() {
      public Aircraft parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Aircraft(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Aircraft> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int POSITION_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Double> position_;
    /**
     * <code>repeated double position = 1;</code>
     */
    public java.util.List<java.lang.Double>
        getPositionList() {
      return position_;
    }
    /**
     * <code>repeated double position = 1;</code>
     */
    public int getPositionCount() {
      return position_.size();
    }
    /**
     * <code>repeated double position = 1;</code>
     */
    public double getPosition(int index) {
      return position_.get(index);
    }

    public static final int SPEED_FIELD_NUMBER = 2;
    private float speed_;
    /**
     * <code>required float speed = 2;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float speed = 2;</code>
     */
    public float getSpeed() {
      return speed_;
    }

    private void initFields() {
      position_ = java.util.Collections.emptyList();
      speed_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < position_.size(); i++) {
        output.writeDouble(1, position_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(2, speed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getPositionList().size();
        size += dataSize;
        size += 1 * getPositionList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, speed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Aircraft}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Aircraft)
        com.atc.simulator.DebugDataFeed.DebugDataFeedServe.AircraftOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.atc.simulator.DebugDataFeed.DebugDataFeedServe.internal_static_Aircraft_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.atc.simulator.DebugDataFeed.DebugDataFeedServe.internal_static_Aircraft_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft.class, com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft.Builder.class);
      }

      // Construct using com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        position_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        speed_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.atc.simulator.DebugDataFeed.DebugDataFeedServe.internal_static_Aircraft_descriptor;
      }

      public com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft getDefaultInstanceForType() {
        return com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft.getDefaultInstance();
      }

      public com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft build() {
        com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft buildPartial() {
        com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft result = new com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          position_ = java.util.Collections.unmodifiableList(position_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.position_ = position_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.speed_ = speed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft) {
          return mergeFrom((com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft other) {
        if (other == com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft.getDefaultInstance()) return this;
        if (!other.position_.isEmpty()) {
          if (position_.isEmpty()) {
            position_ = other.position_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePositionIsMutable();
            position_.addAll(other.position_);
          }
          onChanged();
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSpeed()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.atc.simulator.DebugDataFeed.DebugDataFeedServe.Aircraft) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Double> position_ = java.util.Collections.emptyList();
      private void ensurePositionIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          position_ = new java.util.ArrayList<java.lang.Double>(position_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double position = 1;</code>
       */
      public java.util.List<java.lang.Double>
          getPositionList() {
        return java.util.Collections.unmodifiableList(position_);
      }
      /**
       * <code>repeated double position = 1;</code>
       */
      public int getPositionCount() {
        return position_.size();
      }
      /**
       * <code>repeated double position = 1;</code>
       */
      public double getPosition(int index) {
        return position_.get(index);
      }
      /**
       * <code>repeated double position = 1;</code>
       */
      public Builder setPosition(
          int index, double value) {
        ensurePositionIsMutable();
        position_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double position = 1;</code>
       */
      public Builder addPosition(double value) {
        ensurePositionIsMutable();
        position_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double position = 1;</code>
       */
      public Builder addAllPosition(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensurePositionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, position_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double position = 1;</code>
       */
      public Builder clearPosition() {
        position_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private float speed_ ;
      /**
       * <code>required float speed = 2;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float speed = 2;</code>
       */
      public float getSpeed() {
        return speed_;
      }
      /**
       * <code>required float speed = 2;</code>
       */
      public Builder setSpeed(float value) {
        bitField0_ |= 0x00000002;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float speed = 2;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        speed_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Aircraft)
    }

    static {
      defaultInstance = new Aircraft(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Aircraft)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Aircraft_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Aircraft_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#main/proto/DebugDataFeedServe.proto\"+\n" +
      "\010Aircraft\022\020\n\010position\030\001 \003(\001\022\r\n\005speed\030\002 \002" +
      "(\002B5\n\037com.atc.simulator.DebugDataFeedB\022D" +
      "ebugDataFeedServe"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Aircraft_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Aircraft_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Aircraft_descriptor,
        new java.lang.String[] { "Position", "Speed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
