package com.atc.simulator.Display.Model;

import com.atc.simulator.Display.DisplayCameraListener;
import com.atc.simulator.Display.LayerManager;
import com.atc.simulator.Display.Model.DisplayHud;
import com.atc.simulator.flightdata.DelayedWork.DelayedWorkQueueItem;
import com.atc.simulator.flightdata.DelayedWork.DelayedWorkQueueItemType;
import com.atc.simulator.flightdata.DelayedWork.DelayedWorker;
import com.atc.simulator.flightdata.TimeSource;
import com.badlogic.gdx.graphics.Camera;
import com.badlogic.gdx.utils.ObjectMap;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * Object model for the display
 * @author Luke Frisken
 */
public class Display {
    private LayerManager layerManager;
    private HashMap<String, Camera> cameras;
    private ArrayList<ObjectMap.Entry<DisplayCameraListener, Camera>> cameraListeners;
    private HashMap<DisplayCameraListener, DelayedCameraListener> delayedCameraListenerHashMap;
    private DelayedWorker delayedWorker;
    private static final int WORK_UNITS_PER_FRAME = 100;
    private DisplayHud displayHud;
    private TimeSource timeSource;

    /**
     * Constructor for Display
     */
    public Display(TimeSource timeSource)
    {
        this.timeSource = timeSource;
        cameras = new HashMap<String, Camera>();
        cameraListeners = new ArrayList<ObjectMap.Entry<DisplayCameraListener, Camera>>();
        delayedCameraListenerHashMap = new HashMap<DisplayCameraListener, DelayedCameraListener>();
        delayedWorker = new DelayedWorker(WORK_UNITS_PER_FRAME);
        displayHud = new DisplayHud(this);

    }

    /**
     * Get the layer manager
     * @return the layer manager
     */
    public LayerManager getLayerManager() {
        return layerManager;
    }

    /**
     * Set the display's layer manager
     * @param layerManager the display's layermanager
     */
    public void setLayerManager(LayerManager layerManager) {
        this.layerManager = layerManager;
    }

    /**
     * Add a camera to the display
     * @param cameraName name to reference the camera by
     * @param camera camera object
     */
    public void addCamera(String cameraName, Camera camera)
    {
        cameras.put(cameraName, camera);
    }

    /**
     * get a camera, as referenced by the name it was added with.
     * @param cameraName name referring to a camera in the display.
     * @return camera associated with cameraName provided.
     */
    public Camera getCamera(String cameraName)
    {
        return cameras.get(cameraName);
    }

    /**
     * Get the display's {@link DisplayHud}
     * @return
     */
    public DisplayHud getDisplayHud() {
        return displayHud;
    }

    /**
     * Get the display's time source
     * @return TimeSource the display's time source
     */
    public TimeSource getTimeSource() {
        return timeSource;
    }

    /**
     * A {@link DelayedWorkQueueItemType} which implements display camera listener
     * in order to be able to put updates to models due to changes to the camera into
     * the {@link DelayedWorker}'s queue so that it can be processed gradually
     * rather than bogging down the framerate and doing an update each time the camera changes
     * (which while zooming could be once every frame).
     */
    private class DelayedCameraListener extends DelayedWorkQueueItemType implements DisplayCameraListener
    {
        private DisplayCameraListener originalListener;

        /**
         * Constructor for DelayedCameraListener
         * @param originalListener the original DisplayCameraListener
         * @param priority the priority of this listener
         * @param cost the cost in "work points" for processing work items generated by this
         */
        public DelayedCameraListener(DisplayCameraListener originalListener, int priority, int cost)
        {
            super(priority, cost);
            this.originalListener = originalListener;
        }

        /**
         * The method which is called when the work items that are created using this type
         * need to be processed.
         * @param workItem work item being processed.
         */
        @Override
        public void run(DelayedWorkQueueItem workItem) {
            Object data = workItem.getData();
            CameraUpdate cameraUpdate = (CameraUpdate) data;
            originalListener.onUpdate(cameraUpdate);
        }

        /**
         * Called when the camera has been updated.
         * @param cameraUpdate the data for the camera update
         */
        @Override
        public void onUpdate(CameraUpdate cameraUpdate) {
            delayedWorker.addWorkItem(createWorkItem(cameraUpdate));
        }
    }

    /**
     * Add a new {@link DelayedCameraListener} to this Display and to it's {@link DelayedWorker}.
     * @param camera camera to listen to
     * @param listener listener which will be listening to that camera
     * @param priority priority of work items generated from updates to the camera
     * @param cost cost of work items generated from updates to the camera in "work points"
     */
    public void addDelayedCameraListener(Camera camera, DisplayCameraListener listener, int priority, int cost)
    {
        DelayedCameraListener delayedCameraListener = new DelayedCameraListener(listener, priority, cost);
        delayedWorker.addWorkItemType(delayedCameraListener);
        delayedCameraListenerHashMap.put(listener, delayedCameraListener);
        addCameraListener(camera, delayedCameraListener);
    }

    /**
     * add a camera listener to this display.
     * @param camera the camera being listened too by the listener
     * @param listener listener of type DisplayCameraListener
     */
    public void addCameraListener(Camera camera, DisplayCameraListener listener)
    {
        ObjectMap.Entry entry = new ObjectMap.Entry<DisplayCameraListener, Camera>();
        entry.key = listener;
        entry.value = camera;
        cameraListeners.add(entry);
    }

    /**
     * Remove a camera listener from this display.
     * @param camera camera that the listener was listening to.
     * @param listener listener to remove.
     * @return boolean whether or not a camera listener was removed.
     */
    public boolean removeCameraListener(Camera camera, DisplayCameraListener listener)
    {
        DisplayCameraListener removeListener = listener;
        DelayedCameraListener delayedCameraListener = delayedCameraListenerHashMap.get(removeListener);

        if (delayedCameraListener != null)
        {
            delayedWorker.removeWorkItemType(delayedCameraListener);
            delayedCameraListenerHashMap.remove(removeListener);
            removeListener = delayedCameraListener;
        }


        ArrayList<ObjectMap.Entry> removeEntries = new ArrayList<ObjectMap.Entry>();
        for (ObjectMap.Entry<DisplayCameraListener, Camera> entry : cameraListeners)
        {
            if (entry.key == removeListener && entry.value == camera)
            {
                removeEntries.add(entry);
            }
        }

        for(ObjectMap.Entry entry : removeEntries)
        {
            cameraListeners.remove(entry);
        }




        return removeEntries.size() > 0;
    }

    /**
     * Trigger an update event on a camera in the display.
     * @param cameraUpdate the data for the camera update
     */
    public void triggerCameraOnUpdate(DisplayCameraListener.CameraUpdate cameraUpdate)
    {
        for (ObjectMap.Entry<DisplayCameraListener, Camera> entry : cameraListeners)
        {
            if (entry.value == cameraUpdate.camera)
            {
                entry.key.onUpdate(cameraUpdate);
            }
        }
    }

    /**
     * Update the display
     */
    public void update()
    {
        delayedWorker.run();
    }

}
