// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/PredictionFeedServe.proto

package com.atc.simulator.ProtocolBuffers;

public final class PredictionFeedServe {
  private PredictionFeedServe() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GeographicCoordinateMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GeographicCoordinateMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double altitude = 1;</code>
     */
    boolean hasAltitude();
    /**
     * <code>required double altitude = 1;</code>
     */
    double getAltitude();

    /**
     * <code>required double latitude = 2;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 2;</code>
     */
    double getLatitude();

    /**
     * <code>required double longitude = 3;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 3;</code>
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code GeographicCoordinateMessage}
   */
  public static final class GeographicCoordinateMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GeographicCoordinateMessage)
      GeographicCoordinateMessageOrBuilder {
    // Use GeographicCoordinateMessage.newBuilder() to construct.
    private GeographicCoordinateMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GeographicCoordinateMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GeographicCoordinateMessage defaultInstance;
    public static GeographicCoordinateMessage getDefaultInstance() {
      return defaultInstance;
    }

    public GeographicCoordinateMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GeographicCoordinateMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              altitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              latitude_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              longitude_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PredictionFeedServe.internal_static_GeographicCoordinateMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PredictionFeedServe.internal_static_GeographicCoordinateMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PredictionFeedServe.GeographicCoordinateMessage.class, PredictionFeedServe.GeographicCoordinateMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<GeographicCoordinateMessage> PARSER =
        new com.google.protobuf.AbstractParser<GeographicCoordinateMessage>() {
      public GeographicCoordinateMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GeographicCoordinateMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GeographicCoordinateMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ALTITUDE_FIELD_NUMBER = 1;
    private double altitude_;
    /**
     * <code>required double altitude = 1;</code>
     */
    public boolean hasAltitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double altitude = 1;</code>
     */
    public double getAltitude() {
      return altitude_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 2;
    private double latitude_;
    /**
     * <code>required double latitude = 2;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double latitude = 2;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 3;
    private double longitude_;
    /**
     * <code>required double longitude = 3;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double longitude = 3;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    private void initFields() {
      altitude_ = 0D;
      latitude_ = 0D;
      longitude_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAltitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, altitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, latitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, longitude_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, altitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, latitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, longitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PredictionFeedServe.GeographicCoordinateMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PredictionFeedServe.GeographicCoordinateMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PredictionFeedServe.GeographicCoordinateMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PredictionFeedServe.GeographicCoordinateMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PredictionFeedServe.GeographicCoordinateMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PredictionFeedServe.GeographicCoordinateMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PredictionFeedServe.GeographicCoordinateMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PredictionFeedServe.GeographicCoordinateMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PredictionFeedServe.GeographicCoordinateMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PredictionFeedServe.GeographicCoordinateMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PredictionFeedServe.GeographicCoordinateMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GeographicCoordinateMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GeographicCoordinateMessage)
        PredictionFeedServe.GeographicCoordinateMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PredictionFeedServe.internal_static_GeographicCoordinateMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PredictionFeedServe.internal_static_GeographicCoordinateMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PredictionFeedServe.GeographicCoordinateMessage.class, PredictionFeedServe.GeographicCoordinateMessage.Builder.class);
      }

      // Construct using com.atc.simulator.ProtocolBuffers.PredictionFeedServe.GeographicCoordinateMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        altitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PredictionFeedServe.internal_static_GeographicCoordinateMessage_descriptor;
      }

      public PredictionFeedServe.GeographicCoordinateMessage getDefaultInstanceForType() {
        return PredictionFeedServe.GeographicCoordinateMessage.getDefaultInstance();
      }

      public PredictionFeedServe.GeographicCoordinateMessage build() {
        PredictionFeedServe.GeographicCoordinateMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PredictionFeedServe.GeographicCoordinateMessage buildPartial() {
        PredictionFeedServe.GeographicCoordinateMessage result = new PredictionFeedServe.GeographicCoordinateMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.altitude_ = altitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.longitude_ = longitude_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PredictionFeedServe.GeographicCoordinateMessage) {
          return mergeFrom((PredictionFeedServe.GeographicCoordinateMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PredictionFeedServe.GeographicCoordinateMessage other) {
        if (other == PredictionFeedServe.GeographicCoordinateMessage.getDefaultInstance()) return this;
        if (other.hasAltitude()) {
          setAltitude(other.getAltitude());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAltitude()) {
          
          return false;
        }
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasLongitude()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PredictionFeedServe.GeographicCoordinateMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PredictionFeedServe.GeographicCoordinateMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double altitude_ ;
      /**
       * <code>required double altitude = 1;</code>
       */
      public boolean hasAltitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double altitude = 1;</code>
       */
      public double getAltitude() {
        return altitude_;
      }
      /**
       * <code>required double altitude = 1;</code>
       */
      public Builder setAltitude(double value) {
        bitField0_ |= 0x00000001;
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double altitude = 1;</code>
       */
      public Builder clearAltitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        altitude_ = 0D;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>required double latitude = 2;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double latitude = 2;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 2;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000002;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 2;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>required double longitude = 3;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double longitude = 3;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 3;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000004;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 3;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GeographicCoordinateMessage)
    }

    static {
      defaultInstance = new GeographicCoordinateMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GeographicCoordinateMessage)
  }

  public interface AircraftPredictionMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AircraftPredictionMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string aircraftID = 1;</code>
     */
    boolean hasAircraftID();
    /**
     * <code>required string aircraftID = 1;</code>
     */
    java.lang.String getAircraftID();
    /**
     * <code>required string aircraftID = 1;</code>
     */
    com.google.protobuf.ByteString
        getAircraftIDBytes();

    /**
     * <code>required string time = 2;</code>
     */
    boolean hasTime();
    /**
     * <code>required string time = 2;</code>
     */
    java.lang.String getTime();
    /**
     * <code>required string time = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    /**
     * <code>repeated .GeographicCoordinateMessage position = 3;</code>
     */
    java.util.List<PredictionFeedServe.GeographicCoordinateMessage>
        getPositionList();
    /**
     * <code>repeated .GeographicCoordinateMessage position = 3;</code>
     */
    PredictionFeedServe.GeographicCoordinateMessage getPosition(int index);
    /**
     * <code>repeated .GeographicCoordinateMessage position = 3;</code>
     */
    int getPositionCount();
    /**
     * <code>repeated .GeographicCoordinateMessage position = 3;</code>
     */
    java.util.List<? extends PredictionFeedServe.GeographicCoordinateMessageOrBuilder>
        getPositionOrBuilderList();
    /**
     * <code>repeated .GeographicCoordinateMessage position = 3;</code>
     */
    PredictionFeedServe.GeographicCoordinateMessageOrBuilder getPositionOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AircraftPredictionMessage}
   */
  public static final class AircraftPredictionMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AircraftPredictionMessage)
      AircraftPredictionMessageOrBuilder {
    // Use AircraftPredictionMessage.newBuilder() to construct.
    private AircraftPredictionMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AircraftPredictionMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AircraftPredictionMessage defaultInstance;
    public static AircraftPredictionMessage getDefaultInstance() {
      return defaultInstance;
    }

    public AircraftPredictionMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AircraftPredictionMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              aircraftID_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              time_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                position_ = new java.util.ArrayList<PredictionFeedServe.GeographicCoordinateMessage>();
                mutable_bitField0_ |= 0x00000004;
              }
              position_.add(input.readMessage(PredictionFeedServe.GeographicCoordinateMessage.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          position_ = java.util.Collections.unmodifiableList(position_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PredictionFeedServe.internal_static_AircraftPredictionMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PredictionFeedServe.internal_static_AircraftPredictionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PredictionFeedServe.AircraftPredictionMessage.class, PredictionFeedServe.AircraftPredictionMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<AircraftPredictionMessage> PARSER =
        new com.google.protobuf.AbstractParser<AircraftPredictionMessage>() {
      public AircraftPredictionMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AircraftPredictionMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AircraftPredictionMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int AIRCRAFTID_FIELD_NUMBER = 1;
    private java.lang.Object aircraftID_;
    /**
     * <code>required string aircraftID = 1;</code>
     */
    public boolean hasAircraftID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string aircraftID = 1;</code>
     */
    public java.lang.String getAircraftID() {
      java.lang.Object ref = aircraftID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          aircraftID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string aircraftID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAircraftIDBytes() {
      java.lang.Object ref = aircraftID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aircraftID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private java.lang.Object time_;
    /**
     * <code>required string time = 2;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string time = 2;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string time = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITION_FIELD_NUMBER = 3;
    private java.util.List<PredictionFeedServe.GeographicCoordinateMessage> position_;
    /**
     * <code>repeated .GeographicCoordinateMessage position = 3;</code>
     */
    public java.util.List<PredictionFeedServe.GeographicCoordinateMessage> getPositionList() {
      return position_;
    }
    /**
     * <code>repeated .GeographicCoordinateMessage position = 3;</code>
     */
    public java.util.List<? extends PredictionFeedServe.GeographicCoordinateMessageOrBuilder>
        getPositionOrBuilderList() {
      return position_;
    }
    /**
     * <code>repeated .GeographicCoordinateMessage position = 3;</code>
     */
    public int getPositionCount() {
      return position_.size();
    }
    /**
     * <code>repeated .GeographicCoordinateMessage position = 3;</code>
     */
    public PredictionFeedServe.GeographicCoordinateMessage getPosition(int index) {
      return position_.get(index);
    }
    /**
     * <code>repeated .GeographicCoordinateMessage position = 3;</code>
     */
    public PredictionFeedServe.GeographicCoordinateMessageOrBuilder getPositionOrBuilder(
        int index) {
      return position_.get(index);
    }

    private void initFields() {
      aircraftID_ = "";
      time_ = "";
      position_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAircraftID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPositionCount(); i++) {
        if (!getPosition(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAircraftIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimeBytes());
      }
      for (int i = 0; i < position_.size(); i++) {
        output.writeMessage(3, position_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAircraftIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimeBytes());
      }
      for (int i = 0; i < position_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, position_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PredictionFeedServe.AircraftPredictionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PredictionFeedServe.AircraftPredictionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PredictionFeedServe.AircraftPredictionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PredictionFeedServe.AircraftPredictionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PredictionFeedServe.AircraftPredictionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PredictionFeedServe.AircraftPredictionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PredictionFeedServe.AircraftPredictionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PredictionFeedServe.AircraftPredictionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PredictionFeedServe.AircraftPredictionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PredictionFeedServe.AircraftPredictionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PredictionFeedServe.AircraftPredictionMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AircraftPredictionMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AircraftPredictionMessage)
        PredictionFeedServe.AircraftPredictionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PredictionFeedServe.internal_static_AircraftPredictionMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PredictionFeedServe.internal_static_AircraftPredictionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PredictionFeedServe.AircraftPredictionMessage.class, PredictionFeedServe.AircraftPredictionMessage.Builder.class);
      }

      // Construct using com.atc.simulator.ProtocolBuffers.PredictionFeedServe.AircraftPredictionMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPositionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        aircraftID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (positionBuilder_ == null) {
          position_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          positionBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PredictionFeedServe.internal_static_AircraftPredictionMessage_descriptor;
      }

      public PredictionFeedServe.AircraftPredictionMessage getDefaultInstanceForType() {
        return PredictionFeedServe.AircraftPredictionMessage.getDefaultInstance();
      }

      public PredictionFeedServe.AircraftPredictionMessage build() {
        PredictionFeedServe.AircraftPredictionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PredictionFeedServe.AircraftPredictionMessage buildPartial() {
        PredictionFeedServe.AircraftPredictionMessage result = new PredictionFeedServe.AircraftPredictionMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.aircraftID_ = aircraftID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (positionBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            position_ = java.util.Collections.unmodifiableList(position_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PredictionFeedServe.AircraftPredictionMessage) {
          return mergeFrom((PredictionFeedServe.AircraftPredictionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PredictionFeedServe.AircraftPredictionMessage other) {
        if (other == PredictionFeedServe.AircraftPredictionMessage.getDefaultInstance()) return this;
        if (other.hasAircraftID()) {
          bitField0_ |= 0x00000001;
          aircraftID_ = other.aircraftID_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000002;
          time_ = other.time_;
          onChanged();
        }
        if (positionBuilder_ == null) {
          if (!other.position_.isEmpty()) {
            if (position_.isEmpty()) {
              position_ = other.position_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePositionIsMutable();
              position_.addAll(other.position_);
            }
            onChanged();
          }
        } else {
          if (!other.position_.isEmpty()) {
            if (positionBuilder_.isEmpty()) {
              positionBuilder_.dispose();
              positionBuilder_ = null;
              position_ = other.position_;
              bitField0_ = (bitField0_ & ~0x00000004);
              positionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPositionFieldBuilder() : null;
            } else {
              positionBuilder_.addAllMessages(other.position_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAircraftID()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        for (int i = 0; i < getPositionCount(); i++) {
          if (!getPosition(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PredictionFeedServe.AircraftPredictionMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PredictionFeedServe.AircraftPredictionMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object aircraftID_ = "";
      /**
       * <code>required string aircraftID = 1;</code>
       */
      public boolean hasAircraftID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string aircraftID = 1;</code>
       */
      public java.lang.String getAircraftID() {
        java.lang.Object ref = aircraftID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            aircraftID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string aircraftID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAircraftIDBytes() {
        java.lang.Object ref = aircraftID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          aircraftID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string aircraftID = 1;</code>
       */
      public Builder setAircraftID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        aircraftID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string aircraftID = 1;</code>
       */
      public Builder clearAircraftID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        aircraftID_ = getDefaultInstance().getAircraftID();
        onChanged();
        return this;
      }
      /**
       * <code>required string aircraftID = 1;</code>
       */
      public Builder setAircraftIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        aircraftID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object time_ = "";
      /**
       * <code>required string time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string time = 2;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            time_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string time = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string time = 2;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 2;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>required string time = 2;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }

      private java.util.List<PredictionFeedServe.GeographicCoordinateMessage> position_ =
        java.util.Collections.emptyList();
      private void ensurePositionIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          position_ = new java.util.ArrayList<PredictionFeedServe.GeographicCoordinateMessage>(position_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          PredictionFeedServe.GeographicCoordinateMessage, PredictionFeedServe.GeographicCoordinateMessage.Builder, PredictionFeedServe.GeographicCoordinateMessageOrBuilder> positionBuilder_;

      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public java.util.List<PredictionFeedServe.GeographicCoordinateMessage> getPositionList() {
        if (positionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(position_);
        } else {
          return positionBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public int getPositionCount() {
        if (positionBuilder_ == null) {
          return position_.size();
        } else {
          return positionBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public PredictionFeedServe.GeographicCoordinateMessage getPosition(int index) {
        if (positionBuilder_ == null) {
          return position_.get(index);
        } else {
          return positionBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public Builder setPosition(
          int index, PredictionFeedServe.GeographicCoordinateMessage value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionIsMutable();
          position_.set(index, value);
          onChanged();
        } else {
          positionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public Builder setPosition(
          int index, PredictionFeedServe.GeographicCoordinateMessage.Builder builderForValue) {
        if (positionBuilder_ == null) {
          ensurePositionIsMutable();
          position_.set(index, builderForValue.build());
          onChanged();
        } else {
          positionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public Builder addPosition(PredictionFeedServe.GeographicCoordinateMessage value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionIsMutable();
          position_.add(value);
          onChanged();
        } else {
          positionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public Builder addPosition(
          int index, PredictionFeedServe.GeographicCoordinateMessage value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionIsMutable();
          position_.add(index, value);
          onChanged();
        } else {
          positionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public Builder addPosition(
          PredictionFeedServe.GeographicCoordinateMessage.Builder builderForValue) {
        if (positionBuilder_ == null) {
          ensurePositionIsMutable();
          position_.add(builderForValue.build());
          onChanged();
        } else {
          positionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public Builder addPosition(
          int index, PredictionFeedServe.GeographicCoordinateMessage.Builder builderForValue) {
        if (positionBuilder_ == null) {
          ensurePositionIsMutable();
          position_.add(index, builderForValue.build());
          onChanged();
        } else {
          positionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public Builder addAllPosition(
          java.lang.Iterable<? extends PredictionFeedServe.GeographicCoordinateMessage> values) {
        if (positionBuilder_ == null) {
          ensurePositionIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, position_);
          onChanged();
        } else {
          positionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          positionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public Builder removePosition(int index) {
        if (positionBuilder_ == null) {
          ensurePositionIsMutable();
          position_.remove(index);
          onChanged();
        } else {
          positionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public PredictionFeedServe.GeographicCoordinateMessage.Builder getPositionBuilder(
          int index) {
        return getPositionFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public PredictionFeedServe.GeographicCoordinateMessageOrBuilder getPositionOrBuilder(
          int index) {
        if (positionBuilder_ == null) {
          return position_.get(index);  } else {
          return positionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public java.util.List<? extends PredictionFeedServe.GeographicCoordinateMessageOrBuilder>
           getPositionOrBuilderList() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(position_);
        }
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public PredictionFeedServe.GeographicCoordinateMessage.Builder addPositionBuilder() {
        return getPositionFieldBuilder().addBuilder(
            PredictionFeedServe.GeographicCoordinateMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public PredictionFeedServe.GeographicCoordinateMessage.Builder addPositionBuilder(
          int index) {
        return getPositionFieldBuilder().addBuilder(
            index, PredictionFeedServe.GeographicCoordinateMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .GeographicCoordinateMessage position = 3;</code>
       */
      public java.util.List<PredictionFeedServe.GeographicCoordinateMessage.Builder>
           getPositionBuilderList() {
        return getPositionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          PredictionFeedServe.GeographicCoordinateMessage, PredictionFeedServe.GeographicCoordinateMessage.Builder, PredictionFeedServe.GeographicCoordinateMessageOrBuilder>
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              PredictionFeedServe.GeographicCoordinateMessage, PredictionFeedServe.GeographicCoordinateMessage.Builder, PredictionFeedServe.GeographicCoordinateMessageOrBuilder>(
                  position_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:AircraftPredictionMessage)
    }

    static {
      defaultInstance = new AircraftPredictionMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AircraftPredictionMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeographicCoordinateMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GeographicCoordinateMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AircraftPredictionMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AircraftPredictionMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$main/proto/PredictionFeedServe.proto\"T" +
      "\n\033GeographicCoordinateMessage\022\020\n\010altitud" +
      "e\030\001 \002(\001\022\020\n\010latitude\030\002 \002(\001\022\021\n\tlongitude\030\003" +
      " \002(\001\"m\n\031AircraftPredictionMessage\022\022\n\nair" +
      "craftID\030\001 \002(\t\022\014\n\004time\030\002 \002(\t\022.\n\010position\030" +
      "\003 \003(\0132\034.GeographicCoordinateMessageB:\n#c" +
      "om.atc.simulator.PredictionServiceB\023Pred" +
      "ictionFeedServe"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GeographicCoordinateMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GeographicCoordinateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GeographicCoordinateMessage_descriptor,
        new java.lang.String[] { "Altitude", "Latitude", "Longitude", });
    internal_static_AircraftPredictionMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AircraftPredictionMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AircraftPredictionMessage_descriptor,
        new java.lang.String[] { "AircraftID", "Time", "Position", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
